from dataclasses import dataclass


GENERIC_DOMAIN_LABEL = "generic"


@dataclass(frozen=True)
class DomainProfile:
    label: str
    category: str
    ai_category: str | None
    aliases: tuple[str, ...]
    target_users: tuple[str, ...]
    domain_objects: tuple[str, ...]
    common_workflows: tuple[str, ...]
    feature_templates: dict[str, tuple[str, ...]]
    metric_templates: dict[str, tuple[str, ...]]
    title_nouns: tuple[str, ...]
    risk_templates: tuple[str, ...]
    theme_keywords: dict[str, tuple[str, ...]]
    theme_title_nouns: dict[str, tuple[str, ...]]
    theme_focus: dict[str, str]
    theme_problems: dict[str, str]
    theme_solutions: dict[str, str]
    leakage_terms: tuple[str, ...]


DOMAIN_PROFILES: dict[str, DomainProfile] = {
    "agriculture": DomainProfile(
        label="agriculture",
        category="Agriculture",
        ai_category="AgriTech AI",
        aliases=("agriculture", "agri", "agritech", "farming", "farm", "crop"),
        target_users=("farmers", "agronomists", "farm managers", "agriculture supervisors"),
        domain_objects=(
            "fields",
            "crops",
            "pests",
            "irrigation plans",
            "soil data",
            "yield forecasts",
            "satellite or drone images",
            "farm tasks",
        ),
        common_workflows=(
            "crop monitoring",
            "field planning",
            "pest or disease detection",
            "irrigation recommendation",
            "yield prediction",
            "farm operations reporting",
        ),
        feature_templates={
            "crop_monitoring": (
                "Field and crop data intake",
                "Crop health dashboard with field status",
                "Satellite or drone image review flow",
                "Supervisor report export",
            ),
            "field_planning": (
                "Field mission or route planner",
                "Task assignment for farm teams",
                "Map-based field monitoring view",
                "Supervisor plan approval panel",
            ),
            "pest_detection": (
                "Crop and pest image upload workflow",
                "Pest or disease detection module",
                "Affected field review dashboard",
                "Treatment summary export for supervisors",
            ),
            "irrigation": (
                "Field and soil moisture input flow",
                "Irrigation recommendation module",
                "Watering schedule dashboard",
                "Manager review and report export",
            ),
            "yield_prediction": (
                "Historical field and crop data input",
                "Yield prediction chart",
                "Season comparison dashboard",
                "Farm summary export for supervisors",
            ),
            "obstacle_detection": (
                "Robot or drone mission setup flow",
                "Field obstacle detection workflow",
                "Map-based obstacle review panel",
                "Mission incident export for supervisors",
            ),
            "data_dashboard": (
                "Farm data ingestion workflow",
                "Agricultural data warehouse dashboard",
                "KPI and report generation view",
                "Supervisor reporting panel",
            ),
            "pattern_recognition": (
                "Crop image or sensor data upload",
                "Pattern recognition workflow",
                "Field trend dashboard",
                "Supervisor export for flagged patterns",
            ),
            "general": (
                "Field and crop data input",
                "Farm operations dashboard",
                "Recommendation or monitoring workflow",
                "Supervisor report export",
            ),
        },
        metric_templates={
            "crop_monitoring": (
                "Crop condition detection accuracy",
                "Field status review time",
                "Supervisor usability score",
                "Source alignment score",
            ),
            "field_planning": (
                "Route planning relevance",
                "Task completion rate",
                "API response time",
                "Supervisor usability score",
            ),
            "pest_detection": (
                "Pest detection precision and recall",
                "False positive rate",
                "Case review time",
                "Source alignment score",
            ),
            "irrigation": (
                "Recommendation relevance",
                "Water scheduling accuracy",
                "API response time",
                "Supervisor usability score",
            ),
            "yield_prediction": (
                "Yield prediction error",
                "Forecast update latency",
                "Dashboard usability score",
                "Source alignment score",
            ),
            "obstacle_detection": (
                "Obstacle detection accuracy",
                "Mission response time",
                "Supervisor usability score",
                "Source alignment score",
            ),
            "data_dashboard": (
                "Report generation time",
                "Dashboard task completion rate",
                "Supervisor usability score",
                "Source alignment score",
            ),
            "pattern_recognition": (
                "Pattern classification accuracy",
                "Review turnaround time",
                "API response time",
                "Source alignment score",
            ),
            "general": (
                "Recommendation relevance",
                "API response time",
                "Supervisor usability score",
                "Source alignment score",
            ),
        },
        title_nouns=(
            "Crop Monitor",
            "Field Planner",
            "Pest Detector",
            "Yield Predictor",
            "Irrigation Advisor",
            "Farm Dashboard",
        ),
        risk_templates=(
            "Field data quality may vary across farms and seasons.",
            "Image or sensor coverage may be limited for some crop conditions.",
            "Farm teams may need manual overrides for unusual field scenarios.",
        ),
        theme_keywords={
            "crop_monitoring": ("crop monitoring", "crop health", "field monitoring", "satellite", "drone"),
            "field_planning": ("mission planning", "field layout", "coverage path", "route planning", "planner"),
            "pest_detection": ("pest", "disease", "weed", "blight", "plant disease"),
            "irrigation": ("irrigation", "soil moisture", "watering", "water management"),
            "yield_prediction": ("yield", "harvest", "forecast", "yield prediction"),
            "obstacle_detection": ("obstacle", "collision", "avoidance", "path obstacle"),
            "data_dashboard": ("data warehouse", "dashboard", "analytics", "reporting"),
            "pattern_recognition": ("pattern recognition", "classification", "vision", "recognition"),
        },
        theme_title_nouns={
            "crop_monitoring": ("Smart Crop Monitoring Assistant", "Crop Health Dashboard", "Field Monitor"),
            "field_planning": ("Precision Agriculture Mission Planner", "Field Planner", "Farm Route Planner"),
            "pest_detection": ("Pest Detection Workflow", "Crop Pest Detector", "Field Disease Monitor"),
            "irrigation": ("Irrigation Recommendation Planner", "Irrigation Advisor", "Watering Planner"),
            "yield_prediction": ("Yield Prediction System", "Yield Predictor", "Harvest Forecast Dashboard"),
            "obstacle_detection": ("Farm Field Obstacle Detector", "Mission Safety Monitor", "Field Obstacle Tracker"),
            "data_dashboard": ("Agricultural Data Warehouse Dashboard", "Farm Analytics Dashboard", "Field Operations Dashboard"),
            "pattern_recognition": ("Crop Pattern Recognition System", "Field Pattern Analyzer", "Crop Vision Monitor"),
            "general": ("Farm Operations Dashboard", "Agriculture Workflow Planner", "Crop Management Assistant"),
        },
        theme_focus={
            "crop_monitoring": "crop conditions, field monitoring, and practical farm reporting",
            "field_planning": "field mission planning, route setup, and farm task coordination",
            "pest_detection": "pest or disease recognition, affected-field review, and treatment guidance",
            "irrigation": "soil-aware irrigation planning and farm supervisor review",
            "yield_prediction": "yield forecasting, season comparisons, and decision support",
            "obstacle_detection": "robot or drone mission safety, obstacle review, and field visibility",
            "data_dashboard": "agricultural data warehousing, KPI tracking, and reporting",
            "pattern_recognition": "crop pattern recognition and field trend analysis",
        },
        theme_problems={
            "crop_monitoring": "Farm managers need faster visibility into crop conditions instead of relying only on manual field checks.",
            "field_planning": "Agriculture teams need a clearer way to plan field missions and coordinate practical farm tasks.",
            "pest_detection": "Pests and crop diseases are slow to review manually, which delays treatment decisions for the field team.",
            "irrigation": "Irrigation decisions are often made with incomplete field data, which reduces consistency across farms.",
            "yield_prediction": "Farm supervisors need earlier yield signals rather than waiting for end-of-season summaries.",
            "obstacle_detection": "Field robots or drone missions need safer obstacle-aware planning before deployment in real farm conditions.",
            "data_dashboard": "Farm data is often scattered across spreadsheets and tools, which makes reporting and operational review harder.",
            "pattern_recognition": "Agronomists need a clearer workflow for spotting crop patterns in field imagery or sensor data.",
        },
        theme_solutions={
            "crop_monitoring": "Focus the MVP on field intake, crop status visibility, and supervisor-ready farm summaries.",
            "field_planning": "Focus the MVP on map-backed planning, task coordination, and practical supervisor review.",
            "pest_detection": "Focus the MVP on crop image intake, pest detection, and a concise review workflow for agronomists.",
            "irrigation": "Focus the MVP on soil-aware recommendations, scheduling views, and farm manager review flows.",
            "yield_prediction": "Focus the MVP on forecast generation, comparison charts, and exportable farm summaries.",
            "obstacle_detection": "Focus the MVP on mission setup, obstacle review, and compact safety reporting.",
            "data_dashboard": "Focus the MVP on data ingestion, operational dashboards, and supervisor reporting.",
            "pattern_recognition": "Focus the MVP on field data upload, pattern analysis, and actionable agronomy review.",
        },
        leakage_terms=("crop", "field", "farm", "yield", "irrigation", "soil"),
    ),
    "healthcare": DomainProfile(
        label="healthcare",
        category="Healthcare",
        ai_category="Healthcare AI",
        aliases=("healthcare", "health", "medical", "medicine", "clinical", "hospital", "patient"),
        target_users=("patients", "doctors", "clinic staff", "care coordinators"),
        domain_objects=("patients", "referrals", "clinical cases", "triage notes", "consent records", "care plans"),
        common_workflows=("triage", "referral review", "clinical monitoring", "patient support", "risk prediction"),
        feature_templates={
            "triage": (
                "Patient symptom input form",
                "Urgency scoring workflow",
                "Doctor review dashboard",
                "Case status tracking",
            ),
            "referral": (
                "Referral document upload flow",
                "Clinical text extraction workflow",
                "Doctor routing dashboard",
                "Evidence-linked summary export",
            ),
            "monitoring": (
                "Clinical model or case registry",
                "Performance monitoring dashboard",
                "Alert review workflow",
                "Admin approval panel",
            ),
            "prediction": (
                "Structured patient or claim input",
                "Predictive scoring module",
                "Trend dashboard",
                "Supervisor summary export",
            ),
            "general": (
                "Patient or case intake workflow",
                "Clinical review dashboard",
                "Recommendation or monitoring module",
                "Supervisor export view",
            ),
        },
        metric_templates={
            "triage": ("Triage recommendation relevance", "Precision and recall", "Latency", "Doctor satisfaction score"),
            "referral": ("Referral extraction accuracy", "Precision and recall", "API response time", "Doctor satisfaction score"),
            "monitoring": ("Drift or alert detection accuracy", "Alert response time", "Dashboard usability score", "Source alignment score"),
            "prediction": ("Prediction accuracy", "Mean absolute error", "Latency", "User satisfaction score"),
            "general": ("Response relevance", "Precision and recall", "Latency", "Doctor satisfaction score"),
        },
        title_nouns=("Clinical Monitor", "Triage Assistant", "Referral Analyzer", "Care Dashboard", "Risk Predictor"),
        risk_templates=(
            "Healthcare workflows require careful privacy handling and realistic demo constraints.",
            "Clinical terminology quality can affect extraction and triage outputs.",
            "Supervisor review is needed for higher-risk recommendations.",
        ),
        theme_keywords={
            "triage": ("triage", "symptom", "urgent care", "diagnosis"),
            "referral": ("referral", "clinical note", "document extraction", "case routing"),
            "monitoring": ("lifecycle", "monitor", "drift", "analytics", "mlops"),
            "prediction": ("prediction", "predictive", "risk score", "forecast", "cost"),
        },
        theme_title_nouns={
            "triage": ("Healthcare Triage Assistant", "Clinical Triage Dashboard", "Patient Triage Tool"),
            "referral": ("Healthcare Referral Analyzer", "Clinical Document Analyzer", "Referral Review Dashboard"),
            "monitoring": ("Clinical AI Lifecycle Dashboard", "Healthcare Model Monitor", "AI Operations Dashboard"),
            "prediction": ("Predictive Healthcare Dashboard", "Patient Risk Analyzer", "Healthcare Prediction System"),
            "general": ("Healthcare Support Assistant", "Clinical Review Dashboard", "Care Workflow Tool"),
        },
        theme_focus={
            "triage": "symptom intake, urgency scoring, and guided next-step support",
            "referral": "referral understanding, document analysis, and faster case routing",
            "monitoring": "clinical model monitoring, analytics, and operational visibility",
            "prediction": "risk or cost prediction from structured healthcare inputs",
        },
        theme_problems={
            "triage": "Manual first-level triage can be inconsistent, so teams need a clearer workflow for capturing symptoms and recommending next steps.",
            "referral": "Referral and clinical documents are slow to review manually, which makes prioritization and follow-up harder for the team.",
            "monitoring": "Healthcare AI projects often miss operational visibility, so teams need a clearer way to monitor model behavior and quality over time.",
            "prediction": "Clinicians and admins need earlier signals for patient risk or cost trends instead of relying only on delayed manual analysis.",
        },
        theme_solutions={
            "triage": "Focus the MVP on symptom intake, triage scoring, and escalation support.",
            "referral": "Focus the MVP on referral analysis, evidence extraction, and case-routing support.",
            "monitoring": "Focus the MVP on model monitoring, analytics, and operational dashboard workflows.",
            "prediction": "Focus the MVP on predictive scoring, trend summaries, and explanation views.",
        },
        leakage_terms=("patient", "doctor", "clinical", "healthcare", "medical", "referral"),
    ),
    "education": DomainProfile(
        label="education",
        category="Education",
        ai_category="Education AI",
        aliases=("education", "learning", "student", "students", "course", "teaching", "school"),
        target_users=("students", "teachers", "teaching assistants", "course instructors"),
        domain_objects=("courses", "quizzes", "assignments", "progress records", "study plans", "recommendations"),
        common_workflows=("study guidance", "quiz recommendation", "progress tracking", "teacher review"),
        feature_templates={
            "recommendation": (
                "Student profile and onboarding flow",
                "Lesson or quiz recommendation module",
                "Progress dashboard",
                "Teacher review panel",
            ),
            "assessment": (
                "Quiz or assignment creation flow",
                "Assessment scoring workflow",
                "Weak-topic dashboard",
                "Teacher analytics export",
            ),
            "progress": (
                "Learning plan setup flow",
                "Progress tracking dashboard",
                "Engagement alerts",
                "Instructor summary export",
            ),
            "general": (
                "Student onboarding and profile flow",
                "Learning support or recommendation workflow",
                "Progress dashboard",
                "Teacher review panel",
            ),
        },
        metric_templates={
            "recommendation": ("Recommendation accuracy", "Quiz score improvement", "Engagement rate", "Task completion rate"),
            "assessment": ("Assessment accuracy", "Quiz completion rate", "Feedback turnaround time", "Teacher usability score"),
            "progress": ("Learning improvement rate", "Engagement rate", "Task completion rate", "Instructor usability score"),
            "general": ("Recommendation accuracy", "Task completion rate", "Engagement rate", "Source alignment score"),
        },
        title_nouns=("Learning Assistant", "Progress Dashboard", "Course Planner", "Quiz Coach", "Study Recommender"),
        risk_templates=(
            "Student engagement may vary without realistic course scenarios.",
            "Evaluation quality depends on representative quizzes or assignments.",
            "Teachers may want manual control over final recommendations.",
        ),
        theme_keywords={
            "recommendation": ("recommendation", "personalized learning", "adaptive learning", "study plan"),
            "assessment": ("quiz", "assessment", "grading", "exam", "assignment"),
            "progress": ("progress", "engagement", "retention", "learning analytics"),
        },
        theme_title_nouns={
            "recommendation": ("Smart Learning Assistant", "Study Recommendation Planner", "Personalized Course Guide"),
            "assessment": ("Quiz Performance Dashboard", "Assessment Workflow Coach", "Course Evaluation Assistant"),
            "progress": ("Student Progress Dashboard", "Learning Progress Tracker", "Engagement Review Tool"),
            "general": ("Education Support Assistant", "Course Workflow Planner", "Student Learning Dashboard"),
        },
        theme_focus={
            "recommendation": "personalized guidance, study planning, and practical course support",
            "assessment": "quizzes, assignments, and teacher-facing review workflows",
            "progress": "progress tracking, engagement visibility, and instructor feedback loops",
        },
        theme_problems={
            "recommendation": "Students need more targeted study guidance instead of one-size-fits-all learning support.",
            "assessment": "Teachers need faster ways to review quizzes and highlight weak topics across the course.",
            "progress": "Course teams need clearer visibility into progress and engagement before learners fall behind.",
        },
        theme_solutions={
            "recommendation": "Focus the MVP on student onboarding, personalized recommendations, and a concise teacher review loop.",
            "assessment": "Focus the MVP on quiz workflows, weak-topic analytics, and teacher-facing summaries.",
            "progress": "Focus the MVP on progress tracking, engagement alerts, and instructor review dashboards.",
        },
        leakage_terms=("student", "teacher", "course", "quiz", "learning", "classroom"),
    ),
    "cybersecurity": DomainProfile(
        label="cybersecurity",
        category="Cybersecurity",
        ai_category="Cybersecurity AI",
        aliases=("cybersecurity", "cyber", "security", "phishing", "threat", "soc"),
        target_users=("security analysts", "incident responders", "SOC teams", "security managers"),
        domain_objects=("alerts", "logs", "incidents", "threat scores", "phishing reports", "response notes"),
        common_workflows=("alert triage", "threat detection", "phishing review", "incident response"),
        feature_templates={
            "incident_detection": (
                "Log or alert ingestion workflow",
                "Threat detection module",
                "Incident dashboard",
                "Analyst review panel",
            ),
            "phishing_detection": (
                "Email or report intake flow",
                "Phishing detection workflow",
                "Alert review dashboard",
                "Analyst export summary",
            ),
            "risk_scoring": (
                "Asset or alert input flow",
                "Risk scoring module",
                "Priority queue dashboard",
                "Incident response notes panel",
            ),
            "general": (
                "Alert ingestion workflow",
                "Detection or scoring module",
                "Security dashboard",
                "Analyst review panel",
            ),
        },
        metric_templates={
            "incident_detection": ("Detection precision and recall", "False positive rate", "Alert response time", "Analyst usability score"),
            "phishing_detection": ("Phishing detection precision", "False positive rate", "Review turnaround time", "Source alignment score"),
            "risk_scoring": ("Risk scoring relevance", "Alert response time", "Task completion rate", "Analyst usability score"),
            "general": ("Detection precision and recall", "False positive rate", "Alert response time", "Source alignment score"),
        },
        title_nouns=("Threat Monitor", "Phishing Detector", "Incident Dashboard", "Risk Scorer", "Alert Review Tool"),
        risk_templates=(
            "False positives can reduce analyst trust if detection thresholds are not tuned.",
            "Representative log or phishing samples are needed for meaningful evaluation.",
            "Incident workflows may need manual override for high-severity alerts.",
        ),
        theme_keywords={
            "incident_detection": ("incident", "anomaly", "malware", "breach", "log"),
            "phishing_detection": ("phishing", "email", "spam", "message"),
            "risk_scoring": ("risk score", "priority", "severity", "threat score"),
        },
        theme_title_nouns={
            "incident_detection": ("Threat Incident Dashboard", "Security Alert Monitor", "Incident Detection System"),
            "phishing_detection": ("Phishing Detection Console", "Email Threat Detector", "Phishing Review Dashboard"),
            "risk_scoring": ("Security Risk Scoring Tool", "Threat Priority Dashboard", "Alert Risk Monitor"),
            "general": ("Cybersecurity Workflow Dashboard", "Threat Review Assistant", "Security Operations Monitor"),
        },
        theme_focus={
            "incident_detection": "alert review, incident visibility, and actionable threat response",
            "phishing_detection": "phishing analysis, report review, and analyst-ready triage",
            "risk_scoring": "priority scoring, analyst review, and compact incident workflows",
        },
        theme_problems={
            "incident_detection": "Security teams need faster ways to review alerts and separate actionable incidents from noise.",
            "phishing_detection": "Phishing reports are time-consuming to triage manually, which slows down security response.",
            "risk_scoring": "SOC teams need a clearer way to rank threats before analysts spend time on low-value alerts.",
        },
        theme_solutions={
            "incident_detection": "Focus the MVP on alert ingestion, compact detection logic, and analyst review workflows.",
            "phishing_detection": "Focus the MVP on report intake, phishing scoring, and a concise review dashboard.",
            "risk_scoring": "Focus the MVP on severity scoring, response queues, and analyst-facing summaries.",
        },
        leakage_terms=("threat", "phishing", "incident", "alert", "malware", "breach"),
    ),
    "finance": DomainProfile(
        label="finance",
        category="FinTech",
        ai_category="FinTech AI",
        aliases=("finance", "fintech", "bank", "banking", "payment", "payments", "fraud"),
        target_users=("finance analysts", "operations teams", "compliance reviewers", "product managers"),
        domain_objects=("transactions", "payments", "risk scores", "accounts", "fraud alerts", "ledgers"),
        common_workflows=("fraud review", "payment analytics", "financial forecasting", "compliance review"),
        feature_templates={
            "fraud_detection": (
                "Transaction intake workflow",
                "Fraud detection or scoring module",
                "Operations review dashboard",
                "Analyst export summary",
            ),
            "payment_analytics": (
                "Payment data ingestion flow",
                "Transaction analytics dashboard",
                "Reconciliation or anomaly review",
                "Supervisor report export",
            ),
            "forecasting": (
                "Historical finance data input",
                "Forecasting module",
                "Trend dashboard",
                "Manager summary export",
            ),
            "general": (
                "Transaction or account input workflow",
                "Finance scoring or analytics module",
                "Operations dashboard",
                "Supervisor export panel",
            ),
        },
        metric_templates={
            "fraud_detection": ("Fraud detection precision and recall", "False positive rate", "Review turnaround time", "Source alignment score"),
            "payment_analytics": ("Transaction classification accuracy", "API response time", "Dashboard usability score", "Supervisor usability score"),
            "forecasting": ("Forecast error", "Trend update latency", "Task completion rate", "Source alignment score"),
            "general": ("Recommendation relevance", "API response time", "Task completion rate", "Source alignment score"),
        },
        title_nouns=("Fraud Detector", "Payments Dashboard", "Finance Forecaster", "Risk Scoring Tool", "Transaction Monitor"),
        risk_templates=(
            "Financial datasets may require anonymized scenarios for safe evaluation.",
            "False positives can create extra review load for operations teams.",
            "Compliance expectations may require supervisor overrides in the final workflow.",
        ),
        theme_keywords={
            "fraud_detection": ("fraud", "anomaly", "suspicious transaction", "chargeback"),
            "payment_analytics": ("payment", "transaction", "ledger", "reconciliation", "invoice"),
            "forecasting": ("forecast", "prediction", "portfolio", "revenue", "cost"),
        },
        theme_title_nouns={
            "fraud_detection": ("Transaction Fraud Detector", "Fraud Review Dashboard", "Payment Risk Monitor"),
            "payment_analytics": ("Payments Analytics Dashboard", "Transaction Review Console", "Financial Operations Dashboard"),
            "forecasting": ("Finance Forecasting System", "Revenue Forecast Dashboard", "Portfolio Trend Monitor"),
            "general": ("FinTech Workflow Dashboard", "Finance Operations Planner", "Transaction Analytics Tool"),
        },
        theme_focus={
            "fraud_detection": "transaction review, fraud scoring, and analyst-ready case handling",
            "payment_analytics": "payment visibility, reconciliation support, and operational reporting",
            "forecasting": "financial forecasting, trend analysis, and manager decision support",
        },
        theme_problems={
            "fraud_detection": "Finance teams need quicker ways to review suspicious transactions without flooding analysts with false alarms.",
            "payment_analytics": "Transaction data is hard to review manually across tools, which slows finance operations.",
            "forecasting": "Finance managers need earlier indicators for trends instead of relying only on delayed reporting.",
        },
        theme_solutions={
            "fraud_detection": "Focus the MVP on transaction intake, fraud scoring, and a concise analyst review flow.",
            "payment_analytics": "Focus the MVP on data ingestion, payment dashboards, and exportable ops summaries.",
            "forecasting": "Focus the MVP on trend forecasting, comparison dashboards, and manager-facing summaries.",
        },
        leakage_terms=("payment", "transaction", "fraud", "ledger", "account", "revenue"),
    ),
    "legal": DomainProfile(
        label="legal",
        category="Legal Tech",
        ai_category="Legal Tech AI",
        aliases=("legal", "law", "contract", "court", "compliance", "clause"),
        target_users=("lawyers", "paralegals", "compliance officers", "legal operations managers"),
        domain_objects=("contracts", "clauses", "case notes", "compliance checklists", "legal documents", "review flags"),
        common_workflows=("contract review", "clause extraction", "compliance checking", "case research"),
        feature_templates={
            "contract_review": (
                "Contract upload and intake flow",
                "Clause extraction or review workflow",
                "Legal review dashboard",
                "Annotated export summary",
            ),
            "compliance_workflow": (
                "Policy or regulation intake",
                "Compliance checking module",
                "Issue tracking dashboard",
                "Reviewer export panel",
            ),
            "case_research": (
                "Case or document search workflow",
                "Evidence or precedent summary module",
                "Research dashboard",
                "Paralegal export summary",
            ),
            "general": (
                "Document intake workflow",
                "Legal review or extraction module",
                "Operations dashboard",
                "Reviewer export panel",
            ),
        },
        metric_templates={
            "contract_review": ("Clause extraction accuracy", "Review turnaround time", "Reviewer usability score", "Source alignment score"),
            "compliance_workflow": ("Compliance issue detection accuracy", "Task completion rate", "API response time", "Reviewer usability score"),
            "case_research": ("Evidence retrieval relevance", "Summary usefulness score", "Review turnaround time", "Source alignment score"),
            "general": ("Task completion rate", "API response time", "Reviewer usability score", "Source alignment score"),
        },
        title_nouns=("Contract Analyzer", "Compliance Review Tool", "Legal Research Dashboard", "Clause Extractor", "Case Review Assistant"),
        risk_templates=(
            "Legal language can be ambiguous, which affects extraction quality.",
            "Reviewers may need manual override for sensitive clauses or precedents.",
            "Evaluation quality depends on realistic legal documents and workflows.",
        ),
        theme_keywords={
            "contract_review": ("contract", "clause", "agreement", "document review"),
            "compliance_workflow": ("compliance", "regulation", "audit", "policy"),
            "case_research": ("case law", "precedent", "court", "legal research"),
        },
        theme_title_nouns={
            "contract_review": ("Contract Review Analyzer", "Clause Extraction Dashboard", "Legal Contract Monitor"),
            "compliance_workflow": ("Compliance Workflow Dashboard", "Policy Review Tool", "Legal Compliance Monitor"),
            "case_research": ("Legal Research Assistant", "Case Evidence Dashboard", "Precedent Review Tool"),
            "general": ("Legal Operations Dashboard", "Document Review Assistant", "Law Workflow Planner"),
        },
        theme_focus={
            "contract_review": "document review, clause extraction, and reviewer-ready summaries",
            "compliance_workflow": "policy checking, issue tracking, and legal operations visibility",
            "case_research": "case research, evidence summaries, and practical legal review support",
        },
        theme_problems={
            "contract_review": "Contracts are slow to review manually, especially when teams need to spot risky or missing clauses quickly.",
            "compliance_workflow": "Compliance teams need clearer workflows for tracking issues across policies and regulations.",
            "case_research": "Legal teams need faster ways to summarize documents and highlight relevant evidence for review.",
        },
        theme_solutions={
            "contract_review": "Focus the MVP on contract intake, clause review, and concise reviewer summaries.",
            "compliance_workflow": "Focus the MVP on policy checks, issue dashboards, and exportable compliance reports.",
            "case_research": "Focus the MVP on document search, evidence summaries, and a practical legal review dashboard.",
        },
        leakage_terms=("contract", "clause", "compliance", "case law", "court", "precedent"),
    ),
    "construction": DomainProfile(
        label="construction",
        category="Construction Tech",
        ai_category="Construction Tech AI",
        aliases=("construction", "architecture", "architect", "site", "building", "bim"),
        target_users=("site engineers", "architects", "project managers", "construction supervisors"),
        domain_objects=("site plans", "tasks", "safety incidents", "materials", "drawings", "inspection notes"),
        common_workflows=("site planning", "safety monitoring", "inspection tracking", "progress reporting"),
        feature_templates={
            "site_planning": (
                "Site plan or drawing intake",
                "Task and schedule planning workflow",
                "Project dashboard",
                "Supervisor export summary",
            ),
            "safety_monitoring": (
                "Incident or image upload flow",
                "Safety monitoring workflow",
                "Hazard dashboard",
                "Supervisor review panel",
            ),
            "inspection": (
                "Inspection checklist workflow",
                "Issue tracking module",
                "Progress dashboard",
                "Manager summary export",
            ),
            "general": (
                "Site data intake workflow",
                "Planning or monitoring module",
                "Operations dashboard",
                "Supervisor export panel",
            ),
        },
        metric_templates={
            "site_planning": ("Schedule planning accuracy", "Task completion rate", "Dashboard usability score", "Source alignment score"),
            "safety_monitoring": ("Hazard detection accuracy", "Alert response time", "Supervisor usability score", "Source alignment score"),
            "inspection": ("Inspection completion rate", "Issue turnaround time", "Dashboard usability score", "Supervisor usability score"),
            "general": ("Task completion rate", "API response time", "Supervisor usability score", "Source alignment score"),
        },
        title_nouns=("Site Planner", "Safety Monitor", "Inspection Dashboard", "Project Tracker", "Construction Workflow Tool"),
        risk_templates=(
            "Site workflows vary across projects and may need simplified demo assumptions.",
            "Image-based safety or inspection features depend on representative examples.",
            "Supervisors may need manual overrides for planning and incident review.",
        ),
        theme_keywords={
            "site_planning": ("site planning", "schedule", "layout", "bim", "route"),
            "safety_monitoring": ("safety", "hazard", "helmet", "incident"),
            "inspection": ("inspection", "checklist", "progress", "defect"),
        },
        theme_title_nouns={
            "site_planning": ("Construction Site Planner", "Project Schedule Dashboard", "Site Layout Planner"),
            "safety_monitoring": ("Construction Safety Monitor", "Hazard Review Dashboard", "Site Incident Tracker"),
            "inspection": ("Inspection Workflow Dashboard", "Construction Progress Tracker", "Site Review Tool"),
            "general": ("Construction Operations Dashboard", "Architecture Workflow Planner", "Building Project Monitor"),
        },
        theme_focus={
            "site_planning": "site planning, task coordination, and construction visibility",
            "safety_monitoring": "hazard review, incident visibility, and supervisor-ready monitoring",
            "inspection": "inspection tracking, issue follow-up, and progress reporting",
        },
        theme_problems={
            "site_planning": "Construction teams need clearer ways to coordinate schedules, tasks, and site plans.",
            "safety_monitoring": "Safety incidents and hazards are hard to review quickly without a focused dashboard workflow.",
            "inspection": "Inspection notes and defects are often tracked manually across files, which slows project follow-up.",
        },
        theme_solutions={
            "site_planning": "Focus the MVP on site data intake, planning views, and supervisor coordination.",
            "safety_monitoring": "Focus the MVP on incident intake, hazard review, and compact safety reporting.",
            "inspection": "Focus the MVP on issue tracking, inspection dashboards, and progress summaries.",
        },
        leakage_terms=("site", "building", "inspection", "safety", "architecture", "construction"),
    ),
    "ecommerce": DomainProfile(
        label="ecommerce",
        category="E-commerce",
        ai_category="E-commerce AI",
        aliases=("ecommerce", "e-commerce", "commerce", "shopping", "retail", "store"),
        target_users=("customers", "store managers", "operations teams", "merchants"),
        domain_objects=("products", "orders", "inventory", "recommendations", "carts", "pricing rules"),
        common_workflows=("catalog browsing", "inventory review", "order analytics", "pricing recommendations"),
        feature_templates={
            "inventory": (
                "Catalog or inventory intake flow",
                "Inventory dashboard",
                "Stock alert workflow",
                "Manager export summary",
            ),
            "recommendation": (
                "Customer profile or browsing input",
                "Product recommendation module",
                "Store analytics dashboard",
                "Merchant review panel",
            ),
            "pricing": (
                "Pricing data ingestion workflow",
                "Pricing recommendation module",
                "Trend dashboard",
                "Operations export panel",
            ),
            "general": (
                "Catalog or order intake workflow",
                "Commerce analytics or recommendation module",
                "Store dashboard",
                "Merchant export panel",
            ),
        },
        metric_templates={
            "inventory": ("Inventory alert accuracy", "Task completion rate", "Dashboard usability score", "Source alignment score"),
            "recommendation": ("Recommendation accuracy", "Engagement rate", "Task completion rate", "Merchant usability score"),
            "pricing": ("Pricing recommendation relevance", "Forecast error", "API response time", "Source alignment score"),
            "general": ("Recommendation relevance", "Task completion rate", "Dashboard usability score", "Source alignment score"),
        },
        title_nouns=("Inventory Dashboard", "Product Recommender", "Pricing Planner", "Store Analytics Tool", "Order Monitor"),
        risk_templates=(
            "Catalog and behavior data quality affects recommendation quality.",
            "Merchants may need manual control over pricing and inventory actions.",
            "Evaluation quality depends on realistic store scenarios and KPIs.",
        ),
        theme_keywords={
            "inventory": ("inventory", "stock", "catalog", "warehouse", "order"),
            "recommendation": ("recommendation", "personalization", "customer behavior"),
            "pricing": ("pricing", "price", "demand", "revenue", "promotion"),
        },
        theme_title_nouns={
            "inventory": ("Inventory Operations Dashboard", "Stock Monitoring Console", "Catalog Review Dashboard"),
            "recommendation": ("Product Recommendation Assistant", "Customer Shopping Guide", "Store Recommendation Dashboard"),
            "pricing": ("Pricing Recommendation Planner", "Retail Trend Dashboard", "Commerce Pricing Monitor"),
            "general": ("E-commerce Workflow Dashboard", "Store Operations Planner", "Commerce Analytics Tool"),
        },
        theme_focus={
            "inventory": "inventory visibility, stock alerts, and store operations reporting",
            "recommendation": "product discovery, personalized suggestions, and merchant review workflows",
            "pricing": "pricing decisions, demand trends, and compact operations support",
        },
        theme_problems={
            "inventory": "Store teams need clearer ways to track stock changes before they become order or fulfillment issues.",
            "recommendation": "Customers and merchants need better recommendation workflows than generic catalog sorting.",
            "pricing": "Pricing decisions are hard to tune consistently without trend visibility and review support.",
        },
        theme_solutions={
            "inventory": "Focus the MVP on catalog intake, stock dashboards, and alert summaries.",
            "recommendation": "Focus the MVP on customer inputs, product suggestions, and merchant-facing review.",
            "pricing": "Focus the MVP on pricing analytics, trend dashboards, and practical ops summaries.",
        },
        leakage_terms=("product", "inventory", "order", "cart", "store", "pricing"),
    ),
    "environment": DomainProfile(
        label="environment",
        category="Environment",
        ai_category="Environment AI",
        aliases=("environment", "environmental", "climate", "sustainability", "pollution", "emissions"),
        target_users=("environment analysts", "field inspectors", "sustainability teams", "program managers"),
        domain_objects=("emissions", "air quality readings", "water samples", "waste reports", "sites", "alerts"),
        common_workflows=("emissions monitoring", "waste tracking", "environment reporting", "field inspection review"),
        feature_templates={
            "emissions": (
                "Sensor or report intake workflow",
                "Emissions monitoring dashboard",
                "Threshold alert review",
                "Program manager export summary",
            ),
            "waste": (
                "Waste record intake flow",
                "Waste tracking module",
                "Site dashboard",
                "Supervisor report export",
            ),
            "inspection": (
                "Field inspection workflow",
                "Issue classification module",
                "Program dashboard",
                "Inspector summary export",
            ),
            "general": (
                "Environmental data intake",
                "Monitoring or classification workflow",
                "Program dashboard",
                "Supervisor export panel",
            ),
        },
        metric_templates={
            "emissions": ("Emissions alert accuracy", "API response time", "Dashboard usability score", "Source alignment score"),
            "waste": ("Waste classification accuracy", "Task completion rate", "Supervisor usability score", "Source alignment score"),
            "inspection": ("Issue detection accuracy", "Review turnaround time", "Inspector usability score", "Source alignment score"),
            "general": ("Task completion rate", "API response time", "Usability score", "Source alignment score"),
        },
        title_nouns=("Emissions Monitor", "Waste Tracking Dashboard", "Environmental Review Tool", "Sustainability Dashboard", "Inspection Monitor"),
        risk_templates=(
            "Environmental datasets may be sparse or inconsistent across sites.",
            "Threshold-based alerts may need manual calibration for realistic scenarios.",
            "Inspectors may need manual review for ambiguous classifications.",
        ),
        theme_keywords={
            "emissions": ("emission", "carbon", "air quality", "pollution", "climate"),
            "waste": ("waste", "recycling", "garbage", "disposal"),
            "inspection": ("inspection", "field report", "sample", "site review"),
        },
        theme_title_nouns={
            "emissions": ("Emissions Monitoring Dashboard", "Air Quality Alert Monitor", "Climate Reporting Tool"),
            "waste": ("Waste Tracking Dashboard", "Recycling Review Console", "Environmental Waste Monitor"),
            "inspection": ("Environmental Inspection Monitor", "Site Review Dashboard", "Field Sample Tracker"),
            "general": ("Environment Operations Dashboard", "Sustainability Workflow Planner", "Environmental Analytics Tool"),
        },
        theme_focus={
            "emissions": "emissions visibility, alert handling, and sustainability reporting",
            "waste": "waste tracking, site review, and operational reporting",
            "inspection": "inspection summaries, issue review, and program follow-up",
        },
        theme_problems={
            "emissions": "Sustainability teams need faster visibility into emissions trends and threshold breaches.",
            "waste": "Waste records are often scattered, which makes site-level review and reporting harder.",
            "inspection": "Environmental inspection findings are time-consuming to consolidate manually across reports.",
        },
        theme_solutions={
            "emissions": "Focus the MVP on sensor intake, alert dashboards, and concise sustainability reports.",
            "waste": "Focus the MVP on waste data intake, tracking views, and program summaries.",
            "inspection": "Focus the MVP on inspection workflows, issue dashboards, and compact follow-up reporting.",
        },
        leakage_terms=("emission", "waste", "pollution", "sustainability", "recycling", "climate"),
    ),
    "sports": DomainProfile(
        label="sports",
        category="Sports",
        ai_category="Sports AI",
        aliases=("sports", "sport", "athlete", "team", "match", "training", "fitness"),
        target_users=("coaches", "athletes", "performance analysts", "team managers"),
        domain_objects=("training sessions", "performance stats", "match events", "injury signals", "players", "plans"),
        common_workflows=("performance tracking", "training planning", "injury prevention", "match analytics"),
        feature_templates={
            "performance": (
                "Athlete or match data intake",
                "Performance dashboard",
                "Trend review workflow",
                "Coach export summary",
            ),
            "training": (
                "Training plan setup flow",
                "Session recommendation module",
                "Coach review dashboard",
                "Athlete progress summary",
            ),
            "injury": (
                "Session and workload intake flow",
                "Injury risk monitoring module",
                "Alert dashboard",
                "Coach review panel",
            ),
            "general": (
                "Athlete or team onboarding flow",
                "Performance or planning workflow",
                "Coach dashboard",
                "Team summary export",
            ),
        },
        metric_templates={
            "performance": ("Performance classification accuracy", "Dashboard usability score", "Task completion rate", "Source alignment score"),
            "training": ("Recommendation relevance", "Training plan completion rate", "Coach usability score", "Source alignment score"),
            "injury": ("Risk detection precision and recall", "False positive rate", "Alert response time", "Coach usability score"),
            "general": ("Recommendation relevance", "Task completion rate", "Usability score", "Source alignment score"),
        },
        title_nouns=("Performance Dashboard", "Training Planner", "Injury Monitor", "Match Analytics Tool", "Athlete Review Console"),
        risk_templates=(
            "Training and performance data can vary a lot across teams and sports.",
            "Injury-related recommendations need conservative thresholds and coach review.",
            "Evaluation quality depends on realistic session and match data.",
        ),
        theme_keywords={
            "performance": ("performance", "match analytics", "player stats", "tracking"),
            "training": ("training", "session", "plan", "workout"),
            "injury": ("injury", "fatigue", "load", "strain", "risk"),
        },
        theme_title_nouns={
            "performance": ("Sports Performance Dashboard", "Match Analytics Monitor", "Athlete Performance Tracker"),
            "training": ("Training Recommendation Planner", "Session Planning Dashboard", "Coach Training Assistant"),
            "injury": ("Injury Risk Monitor", "Athlete Safety Dashboard", "Training Load Tracker"),
            "general": ("Sports Workflow Dashboard", "Team Performance Planner", "Athlete Review Assistant"),
        },
        theme_focus={
            "performance": "performance visibility, match analysis, and coach-ready reporting",
            "training": "session planning, recommendation quality, and athlete progress review",
            "injury": "injury risk visibility, alerting, and practical coach oversight",
        },
        theme_problems={
            "performance": "Coaches need clearer performance summaries than raw stats spread across spreadsheets or tools.",
            "training": "Training plans are hard to personalize consistently without structured athlete review workflows.",
            "injury": "Teams need early risk signals before high workloads turn into missed sessions or injuries.",
        },
        theme_solutions={
            "performance": "Focus the MVP on athlete data intake, performance dashboards, and exportable summaries.",
            "training": "Focus the MVP on planning workflows, coach review, and practical athlete summaries.",
            "injury": "Focus the MVP on workload intake, risk alerts, and a compact coach review dashboard.",
        },
        leakage_terms=("athlete", "training", "match", "injury", "coach", "performance"),
    ),
    GENERIC_DOMAIN_LABEL: DomainProfile(
        label=GENERIC_DOMAIN_LABEL,
        category="Software Engineering",
        ai_category="AI",
        aliases=("general", "software", "product", "tool"),
        target_users=("end users", "operators", "supervisors", "admins"),
        domain_objects=("records", "tasks", "reports", "dashboards", "recommendations", "review queues"),
        common_workflows=("data intake", "analysis", "review", "reporting"),
        feature_templates={
            "general": (
                "User input and validation workflow",
                "Core analysis or recommendation module",
                "Main dashboard or task flow",
                "Admin or supervisor review panel",
            )
        },
        metric_templates={
            "general": (
                "Task completion rate",
                "API response time",
                "Usability score",
                "Source alignment score",
            )
        },
        title_nouns=("Workflow Planner", "Operations Dashboard", "Analysis Tool", "Task Monitor"),
        risk_templates=(
            "Scope may expand if the core workflow is not controlled early.",
            "Evaluation quality depends on using realistic demo scenarios.",
            "Late integration changes can slow down the final validation stage.",
        ),
        theme_keywords={
            "prediction": ("prediction", "forecast", "scoring"),
            "dashboard": ("dashboard", "analytics", "monitoring"),
            "planning": ("planner", "planning", "schedule"),
        },
        theme_title_nouns={
            "prediction": ("Prediction Workflow Tool", "Forecast Dashboard", "Scoring Monitor"),
            "dashboard": ("Operations Dashboard", "Analytics Workflow Tool", "Monitoring Console"),
            "planning": ("Workflow Planning Tool", "Task Planning Dashboard", "Operations Planner"),
            "general": ("Source-Backed Workflow Tool", "Operations Dashboard", "Practical Analysis Tool"),
        },
        theme_focus={
            "prediction": "prediction, review visibility, and measurable outcomes",
            "dashboard": "analytics, reporting, and practical operator workflows",
            "planning": "task planning, review loops, and scoped implementation",
        },
        theme_problems={
            "prediction": "Teams need clearer prediction workflows that can be evaluated with practical backend metrics.",
            "dashboard": "Operators need a cleaner way to review information and turn it into actionable decisions.",
            "planning": "Teams need a focused workflow with practical scope instead of a vague broad platform.",
        },
        theme_solutions={
            "prediction": "Focus the MVP on structured inputs, scoring logic, and concise review dashboards.",
            "dashboard": "Focus the MVP on source-backed workflows, reporting, and supervisor-ready views.",
            "planning": "Focus the MVP on a compact task flow, review panel, and measurable backend behavior.",
        },
        leakage_terms=(),
    ),
}
